### ISSUE TITLE
New libyui Widget: YMenuBar

### ISSUE THREAD

**Issue by shundhammer** [libyui/libyui-gtk#73]
(See also https://github.com/manatools/libyui-mga/issues/1)

We added a MenuBar widget to libyui. More details here:

https://github.com/libyui/libyui/pull/169

C++ example:

https://github.com/libyui/libyui/blob/master/examples/MenuBar1.cc

The `YWidgetFactory::createMenuBar()` method right now has a default implementation that just returns a null pointer. Once The Gtk UI implements it, we intend to make it pure virtual in libyui just like the other factory methods.

**Comment by anaselli** [comment]
I think it could be almost finished but please start reviewing it.

I will make more tests also to check if i can use it on our tools before asking for a PR.

**Comment by shundhammer** [comment]
That commit looks good to me (but I am in no way a Gtk expert).

**Comment by anaselli** [comment]
Ok i ported my [YMGAMenuBar  example](https://gist.github.com/anaselli/f243a82ab1dda0898b1334f5386e12b8) and now it uses libyui YMenuBar. 

Please test it.
I experienced a ncurses almost good behavior, but when hidden menu is shown that goes over the windows size:

![immagine](https://user-images.githubusercontent.com/1303486/97919917-e9b1c000-1d58-11eb-9adf-406bbcdd4ecc.png)

Changing menu  (pressing Change menu button) does not refresh new menu though, until on menu an action is taken (selection for instance).
Another issue is on separators, using ncurses that feature is missing:

![immagine](https://user-images.githubusercontent.com/1303486/97920322-92601f80-1d59-11eb-9e5f-990decb84403.png)

The Qt one instead is not respecting the startup menu setup:

![immagine](https://user-images.githubusercontent.com/1303486/97920430-bcb1dd00-1d59-11eb-8da9-123cc0f09c4e.png)

Gtk one seems to be ok:

![immagine](https://user-images.githubusercontent.com/1303486/97920535-e1a65000-1d59-11eb-9ce4-a30491381ff4.png)

**Comment by anaselli** [comment]
In the hope it can help I add here some thoughts.

As far as i can say in a very quick look for Qt i think the problem is in [YQMenuBar::rebuildMenuTree](https://github.com/libyui/libyui-qt/blob/master/src/YQMenuBar.cc#L94) where enablel and visible item properties are not checked.

For ncurses separator i used w.hline(ACS_HLINE, 0); but i know there is a separator NCTableCol::SEPARATOR that maybe you are able to use, i wasn't. Concerning redrawing for new menu i haven't looked at the code, i think a redraw in the right place should fix it.

**Comment by shundhammer** [comment]
> As far as i can say in a very quick look for Qt i think the problem is in YQMenuBar::rebuildMenuTree where enabled and visible item properties are not checked.

You are right. @ancorgs noticed that indepentendly, and it's now fixed, and we also have a new test case:

https://bugzilla.opensuse.org/show_bug.cgi?id=1178394

Fixed with https://github.com/libyui/libyui-qt/pull/139; new test case with https://github.com/yast/yast-ycp-ui-bindings/pull/60 .

**Comment by shundhammer** [comment]
Also fixed initial menu item visibility in the Qt UI.
@anaselli thanks for noticing!

**Comment by anaselli** [comment]
I could ask for a PR then soon, and going on testing by using right issue channels maybe. I'll wait some days to see if the fixing is available on master. Thanks.

**Comment by anaselli** [comment]
> Also fixed initial menu item visibility in the Qt UI.
> @anaselli thanks for noticing!
I pulled libyui-qt but i seem it still does not show initial hidden and disable items... am i wrong in something?

**Comment by shundhammer** [comment]
I can see the commit for initial enabled/disabled state in libyui-qt master:

https://github.com/libyui/libyui-qt/commit/f437e9c36bafd0840b8d62da90ba26dd1fb8e89d

also for initial visibility:

https://github.com/libyui/libyui-qt/commit/5fdcc797ae188e2b58063c595e456d203f1a7390 and https://github.com/libyui/libyui-qt/commit/aa7f13d961028ec9e973b5cd065fa6d2abae97eb

Let me check this with your example https://gist.github.com/anaselli/f243a82ab1dda0898b1334f5386e12b8 when today's long sequence of meetings will finally be done.

**Comment by anaselli** [comment]
sure :) I also asked for a PR ;)

**Comment by anaselli** [comment]
hmm i think i've got it... I added an hidden menu, not an hidden menu item or submenu.

**Comment by shundhammer** [comment]
Ah, okay; that might indeed be missing. But it shouldn't be too hard to add.

**Comment by shundhammer** [comment]
This commit fixes initial visibility and enabled/disabled state for the Qt UI for toplevel menus:

  https://github.com/libyui/libyui-qt/pull/140/commits/61594b6d01158b010e4d4aa5db5d7650f78f47a3

This will become part of the next upcoming PR.

**Comment by anaselli** [comment]
:+1:

**Comment by ancorgs** [comment]
Since the Gtk backend is not developed or maintained by the YaST Team at SUSE, I'm adding the "other-maintainer" label to this in order to help filtering the various list of issues.

**Comment by anaselli** [comment]
I think i reported here some behaviors that should change to ncurses... but as far as libyui-gtk concern i think the issue is fixed
